=begin
#VMware Fusion API 1.2.0

#REST API Explorer

OpenAPI spec version: 1.2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.12

=end

require 'date'

module VMWareFusionClient
  class VMPowerOperation
    
    ON = 'on'.freeze
    OFF = 'off'.freeze
    SHUTDOWN = 'shutdown'.freeze
    SUSPEND = 'suspend'.freeze
    PAUSE = 'pause'.freeze
    UNPAUSE = 'unpause'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = VMPowerOperation.constants.select { |c| VMPowerOperation::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #VMPowerOperation" if constantValues.empty?
      value
    end
  end
end
