=begin
#VMware Fusion API 1.2.0

#REST API Explorer

OpenAPI spec version: 1.2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.12

=end

require 'spec_helper'
require 'json'

# Unit tests for VMWareFusionClient::VMManagementApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VMManagementApi' do
  before do
    # run before each test
    @instance = VMWareFusionClient::VMManagementApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VMManagementApi' do
    it 'should create an instance of VMManagementApi' do
      expect(@instance).to be_instance_of(VMWareFusionClient::VMManagementApi)
    end
  end

  # unit tests for create_vm
  # Creates a copy of the VM
  # @param params Parameters of VM to create
  # @param [Hash] opts the optional parameters
  # @return [VMInformation]
  describe 'create_vm test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_vm
  # Deletes a VM
  # @param id ID of VM
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_vm test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_all_v_ms
  # Returns a list of VM IDs and paths for all VMs
  # @param [Hash] opts the optional parameters
  # @return [Array<VMID>]
  describe 'get_all_v_ms test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_vm
  # Returns the VM setting information of a VM
  # @param id ID of VM
  # @param [Hash] opts the optional parameters
  # @return [VMInformation]
  describe 'get_vm test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_vm
  # Updates the VM settings
  # @param id ID of VM
  # @param parameters VM definition
  # @param [Hash] opts the optional parameters
  # @return [VMInformation]
  describe 'update_vm test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
