=begin
#VMware Fusion API 1.2.0

#REST API Explorer

OpenAPI spec version: 1.2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.12

=end

require 'spec_helper'
require 'json'

# Unit tests for VMWareFusionClient::VMNetworkAdaptersManagementApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VMNetworkAdaptersManagementApi' do
  before do
    # run before each test
    @instance = VMWareFusionClient::VMNetworkAdaptersManagementApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VMNetworkAdaptersManagementApi' do
    it 'should create an instance of VMNetworkAdaptersManagementApi' do
      expect(@instance).to be_instance_of(VMWareFusionClient::VMNetworkAdaptersManagementApi)
    end
  end

  # unit tests for create_nic_device
  # Creates a network adapter in the VM
  # @param id ID of VM
  # @param parameters Parameters of network adapter to create
  # @param [Hash] opts the optional parameters
  # @return [NICDevice]
  describe 'create_nic_device test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_nic_device
  # Deletes a VM network adapter
  # @param id ID of VM
  # @param index Index of VM network adapter
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_nic_device test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_all_nic_devices
  # Returns all network adapters in the VM
  # @param id ID of VM
  # @param [Hash] opts the optional parameters
  # @return [NICDevices]
  describe 'get_all_nic_devices test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_ip_address
  # Returns the IP address of a VM
  # @param id ID of VM
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse200]
  describe 'get_ip_address test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_nic_device
  # Updates a network adapter in the VM
  # @param id ID of VM
  # @param index Index of VM network adapter
  # @param parameters Parameters of network adapter to update to
  # @param [Hash] opts the optional parameters
  # @return [NICDevice]
  describe 'update_nic_device test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
