=begin
#VMware Fusion API 1.2.0

#REST API Explorer

OpenAPI spec version: 1.2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.12

=end

require 'spec_helper'
require 'json'

# Unit tests for VMWareFusionClient::VMPowerManagementApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VMPowerManagementApi' do
  before do
    # run before each test
    @instance = VMWareFusionClient::VMPowerManagementApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VMPowerManagementApi' do
    it 'should create an instance of VMPowerManagementApi' do
      expect(@instance).to be_instance_of(VMWareFusionClient::VMPowerManagementApi)
    end
  end

  # unit tests for change_power_state
  # Changes the VM power state
  # @param id ID of VM
  # @param operation VM power operation: on, off, shutdown, suspend, pause, unpause
  # @param [Hash] opts the optional parameters
  # @return [VMPowerState]
  describe 'change_power_state test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_power_state
  # Returns the power state of the VM
  # @param id ID of VM
  # @param [Hash] opts the optional parameters
  # @return [VMPowerState]
  describe 'get_power_state test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
