=begin
#VMware Fusion API 1.2.0

#REST API Explorer

OpenAPI spec version: 1.2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.12

=end

require 'spec_helper'
require 'json'

# Unit tests for VMWareFusionClient::VMSharedFoldersManagementApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VMSharedFoldersManagementApi' do
  before do
    # run before each test
    @instance = VMWareFusionClient::VMSharedFoldersManagementApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VMSharedFoldersManagementApi' do
    it 'should create an instance of VMSharedFoldersManagementApi' do
      expect(@instance).to be_instance_of(VMWareFusionClient::VMSharedFoldersManagementApi)
    end
  end

  # unit tests for create_shared_folder
  # Mounts a new shared folder in the VM
  # @param id ID of VM
  # @param parameters Parameters of the shared folder to mount
  # @param [Hash] opts the optional parameters
  # @return [SharedFolders]
  describe 'create_shared_folder test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_shared_folder
  # Deletes a shared folder
  # @param id ID of VM
  # @param folder_id ID of shared folder
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_shared_folder test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_all_shared_folders
  # Returns all shared folders mounted in the VM
  # @param id ID of VM
  # @param [Hash] opts the optional parameters
  # @return [SharedFolders]
  describe 'get_all_shared_folders test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for updata_shared_folder
  # Updates a shared folder mounted in the VM
  # @param id ID of VM
  # @param folder_id ID of VM shared folder
  # @param parameters Parameters of the shared folder to update to
  # @param [Hash] opts the optional parameters
  # @return [SharedFolders]
  describe 'updata_shared_folder test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
