=begin
#VMware Fusion API 1.2.0

#REST API Explorer

OpenAPI spec version: 1.2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.12

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VMWareFusionClient::VMPowerState
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VMPowerState' do
  before do
    # run before each test
    @instance = VMWareFusionClient::VMPowerState.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VMPowerState' do
    it 'should create an instance of VMPowerState' do
      expect(@instance).to be_instance_of(VMWareFusionClient::VMPowerState)
    end
  end
  describe 'test attribute "power_state"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["poweredOn", "poweredOff", "paused", "suspended"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.power_state = value }.not_to raise_error
      # end
    end
  end

end
